networks:
  hmpps_int: null

services:
  redis:
    container_name: redis_integration-test
    image: redis:6.2
    networks:
      - hmpps_int
    ports:
      - '6380:6379'

  wiremock:
    container_name: wiremock_integration-test
    image: wiremock/wiremock
    networks:
      - hmpps_int
    ports:
      - '9199:8080'
    restart: always

version: '3.1'
