version: '3.1'
services:
  redis:
    image: 'redis:6.2'
    networks:
      - hmpps_int
    container_name: redis_integration-test
    ports:
      - '6380:6379'

  wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    container_name: wiremock_integration-test
    restart: always
    ports:
      - '9199:8080'

networks:
  hmpps_int:
