#!/bin/sh

echo "==> Starting the backing services in Docker..."

for arg in "$@"
do
  if [[ $arg == "--mock-api" ]]; then
    MOCK_API=true
  fi
done

if [ "$MOCK_API" = true ]; then
  docker compose up --scale=hmpps-accredited-programmes-api=0 --scale=postgresql=0 -d

  echo "==> Stubbing API endpoints..."

  npx ts-node --transpile-only ./wiremock/scripts/resetStubs.ts > /dev/null
  npx ts-node --transpile-only ./wiremock/scripts/stubApis.ts > /dev/null
else
  docker compose up --scale=wiremock=0 -d
fi
