#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

script/utils/launch-docker

echo "==> Installing application dependencies..."

npm_config_yes=true npx @nodenv/nodenv install --skip-existing
npm install
