#!/bin/sh

# script/test: Run the unit tests against your git history, starting at
#              origin/HEAD by default.
#
#              Options:
#                `--start=sha` - start at a different commit, e.g. --start=2hi2hu5
#                `--test="command"` - execute a custom test command, e.g. --test="npm run typecheck"
#
#              Inspired by a Gary Bernhardt script: https://youtu.be/ZQnyApKysg4?t=183

GREEN='\033[1;32m'
RED='\033[1;31m'
RESET_COLOUR='\033[0m'

if [ $(git status --porcelain=v1 2>/dev/null | wc -l) = 1 ]
then
  echo "\n\n${RED}( ͡° ʖ̯ ͡°) Unable to execute script: commit or stash changes and try again${RESET_COLOUR}"
  exit 1
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)
START=origin/HEAD
TEST="npm run test:unit"

for i in "$@"; do
  case $i in
    --start=*)
      START="${i#*=}"
      shift
      ;;
    --test=*)
      TEST="${i#*=}"
      shift
      ;;
    -*|--*)
      echo "Unknown option $i"
      exit 1
      ;;
    *)
      ;;
  esac
done

echo "==> Running \`$TEST\` on all commits from $START to $BRANCH..."

HISTORY=$(git rev-list --reverse $START..$BRANCH)

while read -r revision
do
  git -c advice.detachedHead=false checkout $revision
  eval $TEST
  
  if [ $? != 0 ]
  then
    echo "\n\n${RED}( ͡° ʖ̯ ͡°) Identified bad commit: $revision.${RESET_COLOUR}"
    git checkout $BRANCH
    exit 1
  fi
done <<< "$HISTORY"

echo "\n\n${GREEN}( ͡° ͜ʖ ͡°) History clean!${RESET_COLOUR}"

git checkout $BRANCH
