#!/bin/sh

# script/test: Run the test suite for the application.

set -e

cd "$(dirname "$0")/.."

if [ -n "$DEBUG" ]; then
  set -x
fi

echo "==> Updating..."

script/update

echo "==> Linting the code..."

npm run lint

echo "==> Typechecking the code..."

npm run typecheck

echo "==> Running unit tests..."

npm run test

echo "==> Running integration tests..."

npm run test:integration

cleanup() {
  docker-compose -f docker-compose-test.yml down --remove-orphans
}

trap cleanup EXIT
