#!/bin/sh

# script/test: Run the test suite for the application.

set -e

cd "$(dirname "$0")/.."

if [ -n "$DEBUG" ]; then
  set -x
fi

BUILD=true
UPDATE=true

for arg in "$@"
do
  case $arg in
    --skip-update)
      UPDATE=false
      ;;
    --skip-build)
      BUILD=false
      ;;
  esac
  shift
done

if [ "$UPDATE" = true ]; then
  echo "==> Updating..."

  script/update --skip-backing-service-images
fi

echo "==> Linting the code..."

npm run lint

echo "==> Typechecking the code..."

npm run typecheck

echo "==> Running unit tests..."

npm run test

if [ "$BUILD" = true ]; then
  echo "==> Building..."

  npm run build
fi

echo "==> Running integration tests..."

npm run test:integration

cleanup() {
  docker-compose -f docker-compose-test.yml down --remove-orphans
}

trap cleanup EXIT
