#!/bin/sh

# script/update: Update the application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

echo "==> Pulling latest backing service images..."

docker compose pull

echo "==> Bootstrapping..."

script/bootstrap

echo "==> Updating govuk-frontend types..."

npm run generate-govuk-frontend-types

echo "==> Updating Prison API types..."

script/utils/generateApiTypes/prisonApi

echo "==> Updating Prisoner Search types..."

script/utils/generateApiTypes/prisonerSearch

echo "==> Updating Accredited Programmes API types..."

script/utils/generateApiTypes/accreditedProgrammesApi
