#!/bin/sh

# script/update: Update the application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

echo "==> Pulling latest backing service images..."

docker compose pull

echo "==> Bootstrapping..."

script/bootstrap
