---
# Per environment values which override defaults in hmpps-accredited-programmes-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: accredited-programmes-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-accredited-programmes-dev-cert
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecRuleEngine On
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.paranoia_level=1"

  env:
    ENVIRONMENT: dev
    ACCREDITED_PROGRAMMES_API_URL: 'https://accredited-programmes-api-dev.hmpps.service.justice.gov.uk'
    DPS_URL: 'https://dps-dev.prison.service.justice.gov.uk'
    INGRESS_URL: 'https://accredited-programmes-dev.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in-dev.hmpps.service.justice.gov.uk/auth'
    HMPPS_COMPONENT_API_URL: 'https://frontend-components-dev.hmpps.service.justice.gov.uk'
    HMPPS_MANAGE_USERS_API_URL: 'https://manage-users-api-dev.hmpps.service.justice.gov.uk'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api-dev.prison.service.justice.gov.uk'
    PRISON_API_URL: 'https://prison-api-dev.prison.service.justice.gov.uk'
    PRISON_REGISTER_API_URL: 'https://prison-register-dev.hmpps.service.justice.gov.uk'
    REFER_ENABLED: true

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
