---
# Per environment values which override defaults in hmpps-accredited-programmes-ui/values.yaml

generic-service:
  ingress:
    host: accredited-programmes-preprod.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-accredited-programmes-preprod-cert
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecRuleEngine On
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.paranoia_level=1"

  env:
    ENVIRONMENT: preprod
    ACCREDITED_PROGRAMMES_API_URL: 'https://accredited-programmes-api-preprod.hmpps.service.justice.gov.uk'
    DPS_URL: 'https://dps-preprod.prison.service.justice.gov.uk'
    INGRESS_URL: 'https://accredited-programmes-preprod.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in-preprod.hmpps.service.justice.gov.uk/auth'
    HMPPS_COMPONENT_API_URL: 'https://frontend-components-preprod.hmpps.service.justice.gov.uk'
    HMPPS_MANAGE_USERS_API_URL: 'https://manage-users-api-preprod.hmpps.service.justice.gov.uk'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api-preprod.prison.service.justice.gov.uk'
    PRISON_API_URL: 'https://prison-api-preprod.prison.service.justice.gov.uk'
    PRISON_REGISTER_API_URL: 'https://prison-register-preprod.hmpps.service.justice.gov.uk'
    REFER_ENABLED: true
    CASE_TRANSFER_ENABLED: false

  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons
