name: Git

on:
  pull_request:

jobs:
  message-check:
    name: Block fixup, squash and merge commits

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Block fixup and squash commits
        uses: 13rac1/block-fixup-merge-action@v2.0.0
