name: Build and test node
on:
  workflow_call:
    inputs:
      test_results_artifact_name:
        description: 'Name of uploaded test results artifact; must be unique across pipeline'
        required: false
        type: string
        default: 'npm_integration_test_artifacts'
      node_version_file:
        description: "Passed to setup-node action to specify where to source the version of node from"
        required: false
        type: string
        default: ".nvmrc"
      pre_test_run:
        description: 'Optional command to run before starting the app'
        required: false
        type: string
      app_start_command:
        description: 'Command to start the application'
        required: true
        type: string
      test_command:
        description: 'Command to run the integration tests'
        required: true
        type: string
permissions:
  contents: read
jobs:
  integration_tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=5
      wiremock:
        image: wiremock/wiremock
        ports:
          - 9199:8080
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Use Node.js ${{ inputs.node_version_file }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: ${{ inputs.node_version_file }}
      - name: restore cache
        id: restore-cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7
        env:
          cache-name: node-modules
        with:
          path: |
            ./node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json', '!**/node_modules/**') }}
      - name: download the artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: npm_build_artifacts
      - name: Run pre-test command
        if: ${{ inputs.pre_test_run != '' }}
        run: ${{ inputs.pre_test_run }}
      - name: Start the node app
        run: |
          ${{ inputs.app_start_command }} &
      - name: Wait for node app to start
        run: |
          until curl http://localhost:3007/health > /dev/null 2>&1; do
            printf '.'
            sleep 1
          done
      - name: Run integration tests
        run: ${{ inputs.test_command }}
      - name: upload the artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: ${{ inputs.test_results_artifact_name }}
          path: test_results
      - name: publish test report
        if: ${{ !cancelled() && github.event.repository.visibility == 'public' }}
        uses: dorny/test-reporter@v2
        with:
          artifact: ${{ inputs.test_results_artifact_name }}
          name: Test Report
          path: 'test_results/**/*.xml'
          reporter: java-junit
          fail-on-empty: false
          fail-on-error: false
          list-suites: 'failed'
          list-tests: 'failed'
